Using Test Train Split 

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
df=pd.read_csv("Dataset.csv")
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]
X_train, X_test, Y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [8]:
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, balanced_accuracy_score, confusion_matrix

model = DecisionTreeClassifier(random_state=0)

skf = StratifiedKFold(n_splits=10)
scores = []
precisions = []
specificities = []
sensitivities = []
recalls = []
balanced_accuracies = []
f1_scores = []
confusion_matrices = []

for k, (train_index, test_index) in enumerate(skf.split(X_train, Y_train)):
    X_train_fold, X_test_fold = X_train.iloc[train_index], X_train.iloc[test_index]
    Y_train_fold, Y_test_fold = Y_train.iloc[train_index], Y_train.iloc[test_index]
    
    model.fit(X_train_fold, Y_train_fold)
    y_pred = model.predict(X_test_fold)
    
    score = accuracy_score(Y_test_fold, y_pred)
    precision = precision_score(Y_test_fold, y_pred)
    recall = recall_score(Y_test_fold, y_pred)
    balanced_accuracy = balanced_accuracy_score(Y_test_fold, y_pred)
    f1 = f1_score(Y_test_fold, y_pred)
    confusion = confusion_matrix(Y_test_fold, y_pred)
    
    scores.append(score)
    precisions.append(precision)
    recalls.append(recall)
    balanced_accuracies.append(balanced_accuracy)
    f1_scores.append(f1)
    confusion_matrices.append(confusion)
    
    tn, fp, fn, tp = confusion.ravel()
    specificity = tn / (tn + fp)
    specificities.append(specificity)
    sensitivity = tp / (tp + fn)
    sensitivities.append(sensitivity)

    print('Fold: %2d' % (k+1))
    print('Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
        score, precision, specificity, sensitivity, recall))
    print('Balanced Accuracy: %.3f, F1 Score: %.3f' % (balanced_accuracy, f1))
    print('Confusion Matrix:\n', confusion)
    print('\n')

mean_score = np.mean(scores)
mean_precision = np.mean(precisions)
mean_recall = np.mean(recalls)
mean_balanced_accuracy = np.mean(balanced_accuracies)
mean_f1 = np.mean(f1_scores)
mean_specificity = np.mean(specificities)
mean_sensitivity = np.mean(sensitivities)
mean_confusion = np.mean(confusion_matrices, axis=0)

print('Mean Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
    mean_score, mean_precision, mean_specificity, mean_sensitivity, mean_recall))
print('Mean Balanced Accuracy: %.3f, F1 Score: %.3f' % (mean_balanced_accuracy, mean_f1))
print('Mean Confusion Matrix:\n', mean_confusion)
print('\n\nCross-Validation Accuracy: %.3f +/- %.3f' % (np.mean(scores), np.std(scores)))

Fold:  1
Accuracy: 0.806, Precision: 0.778, Specificity: 0.789, Sensitivity: 0.824, Recall: 0.824
Balanced Accuracy: 0.807, F1 Score: 0.800
Confusion Matrix:
 [[15  4]
 [ 3 14]]


Fold:  2
Accuracy: 0.750, Precision: 0.750, Specificity: 0.789, Sensitivity: 0.706, Recall: 0.706
Balanced Accuracy: 0.748, F1 Score: 0.727
Confusion Matrix:
 [[15  4]
 [ 5 12]]


Fold:  3
Accuracy: 0.833, Precision: 0.824, Specificity: 0.842, Sensitivity: 0.824, Recall: 0.824
Balanced Accuracy: 0.833, F1 Score: 0.824
Confusion Matrix:
 [[16  3]
 [ 3 14]]


Fold:  4
Accuracy: 0.722, Precision: 0.700, Specificity: 0.667, Sensitivity: 0.778, Recall: 0.778
Balanced Accuracy: 0.722, F1 Score: 0.737
Confusion Matrix:
 [[12  6]
 [ 4 14]]


Fold:  5
Accuracy: 0.667, Precision: 0.650, Specificity: 0.611, Sensitivity: 0.722, Recall: 0.722
Balanced Accuracy: 0.667, F1 Score: 0.684
Confusion Matrix:
 [[11  7]
 [ 5 13]]


Fold:  6
Accuracy: 0.611, Precision: 0.625, Specificity: 0.667, Sensitivity: 0.556, Recall: 0.556
Ba

Using seperate Test and Train Data

In [9]:
d=pd.read_csv("TestDataset.csv")
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]
x_test=d.iloc[:,:-1]
y_test=d.iloc[:,-1]

In [10]:
from sklearn.model_selection import StratifiedKFold
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, balanced_accuracy_score, confusion_matrix

strtfdKFold = StratifiedKFold(n_splits=10)
kfold = strtfdKFold.split(X, Y)

scores = []
precisions = []
specificities = []
sensitivities = []
recalls = []
balanced_accuracies = []
f1_scores = []
confusion_matrices = []

model = DecisionTreeClassifier(random_state=0)

for k, (train, test) in enumerate(kfold):
    model.fit(X.iloc[train], Y.iloc[train])
    y_pred = model.predict(X.iloc[test])
    score = accuracy_score(Y.iloc[test], y_pred)
    precision = precision_score(Y.iloc[test], y_pred)
    recall = recall_score(Y.iloc[test], y_pred)
    balanced_accuracy = balanced_accuracy_score(Y.iloc[test], y_pred)
    f1 = f1_score(Y.iloc[test], y_pred)
    confusion = confusion_matrix(Y.iloc[test], y_pred)

    scores.append(score)
    precisions.append(precision)
    recalls.append(recall)
    balanced_accuracies.append(balanced_accuracy)
    f1_scores.append(f1)
    confusion_matrices.append(confusion)

    tn, fp, fn, tp = confusion.ravel()
    specificity = tn / (tn + fp)
    specificities.append(specificity)
    sensitivity = tp / (tp + fn)
    sensitivities.append(sensitivity)

    print('Fold: %2d, Training/Test Split Distribution: %s' % (k + 1, np.bincount(Y.iloc[train])))
    print('Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
    score, precision, specificity, sensitivity, recall))
    print('Balanced Accuracy: %.3f, F1 Score: %.3f' % (balanced_accuracy, f1))
    print('Confusion Matrix:\n', confusion)
    print('\n')

print('\n\nCross-Validation Accuracy: %.3f +/- %.3f' % (np.mean(scores), np.std(scores)))
mean_score = np.mean(scores)
mean_precision = np.mean(precisions)
mean_recall = np.mean(recalls)
mean_balanced_accuracy = np.mean(balanced_accuracies)
mean_f1 = np.mean(f1_scores)
mean_specificity = np.mean(specificities)
mean_sensitivity = np.mean(sensitivities)
mean_confusion = np.mean(confusion_matrices, axis=0)

print('Mean Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
    mean_score, mean_precision, mean_specificity, mean_sensitivity, mean_recall))
print('Mean Balanced Accuracy: %.3f, F1 Score: %.3f' % (mean_balanced_accuracy, mean_f1))
print('Mean Confusion Matrix:\n', mean_confusion)
print('\n\nCross-Validation Accuracy: %.3f +/- %.3f' % (np.mean(scores), np.std(scores)))


Fold:  1, Training/Test Split Distribution: [204 198]
Accuracy: 0.756, Precision: 0.762, Specificity: 0.783, Sensitivity: 0.727, Recall: 0.727
Balanced Accuracy: 0.755, F1 Score: 0.744
Confusion Matrix:
 [[18  5]
 [ 6 16]]


Fold:  2, Training/Test Split Distribution: [204 198]
Accuracy: 0.711, Precision: 0.667, Specificity: 0.609, Sensitivity: 0.818, Recall: 0.818
Balanced Accuracy: 0.713, F1 Score: 0.735
Confusion Matrix:
 [[14  9]
 [ 4 18]]


Fold:  3, Training/Test Split Distribution: [204 198]
Accuracy: 0.889, Precision: 0.947, Specificity: 0.957, Sensitivity: 0.818, Recall: 0.818
Balanced Accuracy: 0.887, F1 Score: 0.878
Confusion Matrix:
 [[22  1]
 [ 4 18]]


Fold:  4, Training/Test Split Distribution: [204 198]
Accuracy: 0.622, Precision: 0.600, Specificity: 0.565, Sensitivity: 0.682, Recall: 0.682
Balanced Accuracy: 0.624, F1 Score: 0.638
Confusion Matrix:
 [[13 10]
 [ 7 15]]


Fold:  5, Training/Test Split Distribution: [204 198]
Accuracy: 0.733, Precision: 0.727, Specificity