Using Test Train Split

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
df=pd.read_csv("Dataset.csv")
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]
X_train, X_test, Y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [3]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, balanced_accuracy_score, confusion_matrix

model = KNeighborsClassifier(n_neighbors=3)

skf = StratifiedKFold(n_splits=10)
scores = []
precisions = []
specificities = []
sensitivities = []
recalls = []
balanced_accuracies = []
f1_scores = []
confusion_matrices = []

for k, (train_index, test_index) in enumerate(skf.split(X_train, Y_train)):
    X_train_fold, X_test_fold = X_train.iloc[train_index], X_train.iloc[test_index]
    Y_train_fold, Y_test_fold = Y_train.iloc[train_index], Y_train.iloc[test_index]
    
    model.fit(X_train_fold, Y_train_fold)
    y_pred = model.predict(X_test_fold)
    
    score = accuracy_score(Y_test_fold, y_pred)
    precision = precision_score(Y_test_fold, y_pred)
    recall = recall_score(Y_test_fold, y_pred)
    balanced_accuracy = balanced_accuracy_score(Y_test_fold, y_pred)
    f1 = f1_score(Y_test_fold, y_pred)
    confusion = confusion_matrix(Y_test_fold, y_pred)
    
    scores.append(score)
    precisions.append(precision)
    recalls.append(recall)
    balanced_accuracies.append(balanced_accuracy)
    f1_scores.append(f1)
    confusion_matrices.append(confusion)
    
    tn, fp, fn, tp = confusion.ravel()
    specificity = tn / (tn + fp)
    specificities.append(specificity)
    sensitivity = tp / (tp + fn)
    sensitivities.append(sensitivity)

    print('Fold: %2d' % (k+1))
    print('Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
        score, precision, specificity, sensitivity, recall))
    print('Balanced Accuracy: %.3f, F1 Score: %.3f' % (balanced_accuracy, f1))
    print('Confusion Matrix:\n', confusion)
    print('\n')

mean_score = np.mean(scores)
mean_precision = np.mean(precisions)
mean_recall = np.mean(recalls)
mean_balanced_accuracy = np.mean(balanced_accuracies)
mean_f1 = np.mean(f1_scores)
mean_specificity = np.mean(specificities)
mean_sensitivity = np.mean(sensitivities)
mean_confusion = np.mean(confusion_matrices, axis=0)

print('Mean Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
    mean_score, mean_precision, mean_specificity, mean_sensitivity, mean_recall))
print('Mean Balanced Accuracy: %.3f, F1 Score: %.3f' % (mean_balanced_accuracy, mean_f1))
print('Mean Confusion Matrix:\n', mean_confusion)
print('\n\nCross-Validation Accuracy: %.3f +/- %.3f' % (np.mean(scores), np.std(scores)))

Fold:  1
Accuracy: 0.667, Precision: 0.688, Specificity: 0.722, Sensitivity: 0.611, Recall: 0.611
Balanced Accuracy: 0.667, F1 Score: 0.647
Confusion Matrix:
 [[13  5]
 [ 7 11]]


Fold:  2
Accuracy: 0.556, Precision: 0.550, Specificity: 0.500, Sensitivity: 0.611, Recall: 0.611
Balanced Accuracy: 0.556, F1 Score: 0.579
Confusion Matrix:
 [[ 9  9]
 [ 7 11]]


Fold:  3
Accuracy: 0.611, Precision: 0.700, Specificity: 0.833, Sensitivity: 0.389, Recall: 0.389
Balanced Accuracy: 0.611, F1 Score: 0.500
Confusion Matrix:
 [[15  3]
 [11  7]]


Fold:  4
Accuracy: 0.667, Precision: 0.667, Specificity: 0.667, Sensitivity: 0.667, Recall: 0.667
Balanced Accuracy: 0.667, F1 Score: 0.667
Confusion Matrix:
 [[12  6]
 [ 6 12]]


Fold:  5
Accuracy: 0.611, Precision: 0.625, Specificity: 0.667, Sensitivity: 0.556, Recall: 0.556
Balanced Accuracy: 0.611, F1 Score: 0.588
Confusion Matrix:
 [[12  6]
 [ 8 10]]


Fold:  6
Accuracy: 0.778, Precision: 0.778, Specificity: 0.778, Sensitivity: 0.778, Recall: 0.778
Ba

Using Seperate Train & Test Data

In [4]:
d=pd.read_csv("TestDataset.csv")
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]
x_test=d.iloc[:,:-1]
y_test=d.iloc[:,-1]

In [5]:
from sklearn.model_selection import StratifiedKFold
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, balanced_accuracy_score, confusion_matrix

strtfdKFold = StratifiedKFold(n_splits=10)
kfold = strtfdKFold.split(X, Y)

scores = []
precisions = []
specificities = []
sensitivities = []
recalls = []
balanced_accuracies = []
f1_scores = []
confusion_matrices = []

model = KNeighborsClassifier(n_neighbors=3)

for k, (train, test) in enumerate(kfold):
    model.fit(X.iloc[train], Y.iloc[train])
    y_pred = model.predict(X.iloc[test])
    score = accuracy_score(Y.iloc[test], y_pred)
    precision = precision_score(Y.iloc[test], y_pred)
    recall = recall_score(Y.iloc[test], y_pred)
    balanced_accuracy = balanced_accuracy_score(Y.iloc[test], y_pred)
    f1 = f1_score(Y.iloc[test], y_pred)
    confusion = confusion_matrix(Y.iloc[test], y_pred)

    scores.append(score)
    precisions.append(precision)
    recalls.append(recall)
    balanced_accuracies.append(balanced_accuracy)
    f1_scores.append(f1)
    confusion_matrices.append(confusion)

    tn, fp, fn, tp = confusion.ravel()
    specificity = tn / (tn + fp)
    specificities.append(specificity)
    sensitivity = tp / (tp + fn)
    sensitivities.append(sensitivity)

    print('Fold: %2d, Training/Test Split Distribution: %s' % (k + 1, np.bincount(Y.iloc[train])))
    print('Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
    score, precision, specificity, sensitivity, recall))
    print('Balanced Accuracy: %.3f, F1 Score: %.3f' % (balanced_accuracy, f1))
    print('Confusion Matrix:\n', confusion)
    print('\n')

print('\n\nCross-Validation Accuracy: %.3f +/- %.3f' % (np.mean(scores), np.std(scores)))
mean_score = np.mean(scores)
mean_precision = np.mean(precisions)
mean_recall = np.mean(recalls)
mean_balanced_accuracy = np.mean(balanced_accuracies)
mean_f1 = np.mean(f1_scores)
mean_specificity = np.mean(specificities)
mean_sensitivity = np.mean(sensitivities)
mean_confusion = np.mean(confusion_matrices, axis=0)

print('Mean Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
    mean_score, mean_precision, mean_specificity, mean_sensitivity, mean_recall))
print('Mean Balanced Accuracy: %.3f, F1 Score: %.3f' % (mean_balanced_accuracy, mean_f1))
print('Mean Confusion Matrix:\n', mean_confusion)
print('\n\nCross-Validation Accuracy: %.3f +/- %.3f' % (np.mean(scores), np.std(scores)))

Fold:  1, Training/Test Split Distribution: [204 198]
Accuracy: 0.511, Precision: 0.500, Specificity: 0.522, Sensitivity: 0.500, Recall: 0.500
Balanced Accuracy: 0.511, F1 Score: 0.500
Confusion Matrix:
 [[12 11]
 [11 11]]


Fold:  2, Training/Test Split Distribution: [204 198]
Accuracy: 0.600, Precision: 0.643, Specificity: 0.783, Sensitivity: 0.409, Recall: 0.409
Balanced Accuracy: 0.596, F1 Score: 0.500
Confusion Matrix:
 [[18  5]
 [13  9]]


Fold:  3, Training/Test Split Distribution: [204 198]
Accuracy: 0.667, Precision: 0.769, Specificity: 0.870, Sensitivity: 0.455, Recall: 0.455
Balanced Accuracy: 0.662, F1 Score: 0.571
Confusion Matrix:
 [[20  3]
 [12 10]]


Fold:  4, Training/Test Split Distribution: [204 198]
Accuracy: 0.222, Precision: 0.190, Specificity: 0.261, Sensitivity: 0.182, Recall: 0.182
Balanced Accuracy: 0.221, F1 Score: 0.186
Confusion Matrix:
 [[ 6 17]
 [18  4]]


Fold:  5, Training/Test Split Distribution: [204 198]
Accuracy: 0.667, Precision: 0.667, Specificity