Using Test Train Split

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
df=pd.read_csv("Dataset.csv")
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]
X_train, X_test, Y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [2]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, balanced_accuracy_score, confusion_matrix

model = LogisticRegression()

skf = StratifiedKFold(n_splits=10)
scores = []
precisions = []
specificities = []
sensitivities = []
recalls = []
balanced_accuracies = []
f1_scores = []
confusion_matrices = []

for k, (train_index, test_index) in enumerate(skf.split(X_train, Y_train)):
    X_train_fold, X_test_fold = X_train.iloc[train_index], X_train.iloc[test_index]
    Y_train_fold, Y_test_fold = Y_train.iloc[train_index], Y_train.iloc[test_index]
    
    model.fit(X_train_fold, Y_train_fold)
    y_pred = model.predict(X_test_fold)
    
    score = accuracy_score(Y_test_fold, y_pred)
    precision = precision_score(Y_test_fold, y_pred)
    recall = recall_score(Y_test_fold, y_pred)
    balanced_accuracy = balanced_accuracy_score(Y_test_fold, y_pred)
    f1 = f1_score(Y_test_fold, y_pred)
    confusion = confusion_matrix(Y_test_fold, y_pred)
    
    scores.append(score)
    precisions.append(precision)
    recalls.append(recall)
    balanced_accuracies.append(balanced_accuracy)
    f1_scores.append(f1)
    confusion_matrices.append(confusion)
    
    tn, fp, fn, tp = confusion.ravel()
    specificity = tn / (tn + fp)
    specificities.append(specificity)
    sensitivity = tp / (tp + fn)
    sensitivities.append(sensitivity)

    print('Fold: %2d' % (k+1))
    print('Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
        score, precision, specificity, sensitivity, recall))
    print('Balanced Accuracy: %.3f, F1 Score: %.3f' % (balanced_accuracy, f1))
    print('Confusion Matrix:\n', confusion)
    print('\n')

mean_score = np.mean(scores)
mean_precision = np.mean(precisions)
mean_recall = np.mean(recalls)
mean_balanced_accuracy = np.mean(balanced_accuracies)
mean_f1 = np.mean(f1_scores)
mean_specificity = np.mean(specificities)
mean_sensitivity = np.mean(sensitivities)
mean_confusion = np.mean(confusion_matrices, axis=0)

print('Mean Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
    mean_score, mean_precision, mean_specificity, mean_sensitivity, mean_recall))
print('Mean Balanced Accuracy: %.3f, F1 Score: %.3f' % (mean_balanced_accuracy, mean_f1))
print('Mean Confusion Matrix:\n', mean_confusion)
print('\n\nCross-Validation Accuracy: %.3f +/- %.3f' % (np.mean(scores), np.std(scores)))

C:\Users\sanja\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\sanja\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Fold:  1
Accuracy: 0.556, Precision: 0.562, Specificity: 0.611, Sensitivity: 0.500, Recall: 0.500
Balanced Accuracy: 0.556, F1 Score: 0.529
Confusion Matrix:
 [[11  7]
 [ 9  9]]


Fold:  2
Accuracy: 0.667, Precision: 0.714, Specificity: 0.778, Sensitivity: 0.556, Recall: 0.556
Balanced Accuracy: 0.667, F1 Score: 0.625
Confusion Matrix:
 [[14  4]
 [ 8 10]]


Fold:  3
Accuracy: 0.722, Precision: 0.700, Specificity: 0.667, Sensitivity: 0.778, Recall: 0.778
Balanced Accuracy: 0.722, F1 Score: 0.737
Confusion Matrix:
 [[12  6]
 [ 4 14]]




C:\Users\sanja\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\sanja\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Fold:  4
Accuracy: 0.639, Precision: 0.647, Specificity: 0.667, Sensitivity: 0.611, Recall: 0.611
Balanced Accuracy: 0.639, F1 Score: 0.629
Confusion Matrix:
 [[12  6]
 [ 7 11]]


Fold:  5
Accuracy: 0.750, Precision: 0.750, Specificity: 0.789, Sensitivity: 0.706, Recall: 0.706
Balanced Accuracy: 0.748, F1 Score: 0.727
Confusion Matrix:
 [[15  4]
 [ 5 12]]


Fold:  6
Accuracy: 0.722, Precision: 0.733, Specificity: 0.789, Sensitivity: 0.647, Recall: 0.647
Balanced Accuracy: 0.718, F1 Score: 0.688
Confusion Matrix:
 [[15  4]
 [ 6 11]]


Fold:  7
Accuracy: 0.528, Precision: 0.500, Specificity: 0.632, Sensitivity: 0.412, Recall: 0.412
Balanced Accuracy: 0.522, F1 Score: 0.452
Confusion Matrix:
 [[12  7]
 [10  7]]


Fold:  8
Accuracy: 0.771, Precision: 0.800, Specificity: 0.833, Sensitivity: 0.706, Recall: 0.706
Balanced Accuracy: 0.770, F1 Score: 0.750
Confusion Matrix:
 [[15  3]
 [ 5 12]]


Fold:  9
Accuracy: 0.771, Precision: 0.846, Specificity: 0.889, Sensitivity: 0.647, Recall: 0.647
Ba

C:\Users\sanja\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\sanja\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Using Seperate Test & Train Dataset

In [3]:
d=pd.read_csv("TestDataset.csv")
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]
x_test=d.iloc[:,:-1]
y_test=d.iloc[:,-1]

In [4]:
from sklearn.model_selection import StratifiedKFold
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, balanced_accuracy_score, confusion_matrix

strtfdKFold = StratifiedKFold(n_splits=10)
kfold = strtfdKFold.split(X, Y)

scores = []
precisions = []
specificities = []
sensitivities = []
recalls = []
balanced_accuracies = []
f1_scores = []
confusion_matrices = []

model = LogisticRegression()

for k, (train, test) in enumerate(kfold):
    model.fit(X.iloc[train], Y.iloc[train])
    y_pred = model.predict(X.iloc[test])
    score = accuracy_score(Y.iloc[test], y_pred)
    precision = precision_score(Y.iloc[test], y_pred)
    recall = recall_score(Y.iloc[test], y_pred)
    balanced_accuracy = balanced_accuracy_score(Y.iloc[test], y_pred)
    f1 = f1_score(Y.iloc[test], y_pred)
    confusion = confusion_matrix(Y.iloc[test], y_pred)

    scores.append(score)
    precisions.append(precision)
    recalls.append(recall)
    balanced_accuracies.append(balanced_accuracy)
    f1_scores.append(f1)
    confusion_matrices.append(confusion)

    tn, fp, fn, tp = confusion.ravel()
    specificity = tn / (tn + fp)
    specificities.append(specificity)
    sensitivity = tp / (tp + fn)
    sensitivities.append(sensitivity)

    print('Fold: %2d, Training/Test Split Distribution: %s' % (k + 1, np.bincount(Y.iloc[train])))
    print('Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
    score, precision, specificity, sensitivity, recall))
    print('Balanced Accuracy: %.3f, F1 Score: %.3f' % (balanced_accuracy, f1))
    print('Confusion Matrix:\n', confusion)
    print('\n')

print('\n\nCross-Validation Accuracy: %.3f +/- %.3f' % (np.mean(scores), np.std(scores)))
mean_score = np.mean(scores)
mean_precision = np.mean(precisions)
mean_recall = np.mean(recalls)
mean_balanced_accuracy = np.mean(balanced_accuracies)
mean_f1 = np.mean(f1_scores)
mean_specificity = np.mean(specificities)
mean_sensitivity = np.mean(sensitivities)
mean_confusion = np.mean(confusion_matrices, axis=0)

print('Mean Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
    mean_score, mean_precision, mean_specificity, mean_sensitivity, mean_recall))
print('Mean Balanced Accuracy: %.3f, F1 Score: %.3f' % (mean_balanced_accuracy, mean_f1))
print('Mean Confusion Matrix:\n', mean_confusion)
print('\n\nCross-Validation Accuracy: %.3f +/- %.3f' % (np.mean(scores), np.std(scores)))

C:\Users\sanja\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\sanja\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Fold:  1, Training/Test Split Distribution: [204 198]
Accuracy: 0.644, Precision: 0.636, Specificity: 0.652, Sensitivity: 0.636, Recall: 0.636
Balanced Accuracy: 0.644, F1 Score: 0.636
Confusion Matrix:
 [[15  8]
 [ 8 14]]


Fold:  2, Training/Test Split Distribution: [204 198]
Accuracy: 0.711, Precision: 0.667, Specificity: 0.609, Sensitivity: 0.818, Recall: 0.818
Balanced Accuracy: 0.713, F1 Score: 0.735
Confusion Matrix:
 [[14  9]
 [ 4 18]]


Fold:  3, Training/Test Split Distribution: [204 198]
Accuracy: 0.733, Precision: 0.708, Specificity: 0.696, Sensitivity: 0.773, Recall: 0.773
Balanced Accuracy: 0.734, F1 Score: 0.739
Confusion Matrix:
 [[16  7]
 [ 5 17]]


Fold:  4, Training/Test Split Distribution: [204 198]
Accuracy: 0.778, Precision: 0.773, Specificity: 0.783, Sensitivity: 0.773, Recall: 0.773
Balanced Accuracy: 0.778, F1 Score: 0.773
Confusion Matrix:
 [[18  5]
 [ 5 17]]


Fold:  5, Training/Test Split Distribution: [204 198]
Accuracy: 0.489, Precision: 0.483, Specificity

C:\Users\sanja\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\sanja\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Fold:  7, Training/Test Split Distribution: [204 198]
Accuracy: 0.622, Precision: 0.667, Specificity: 0.783, Sensitivity: 0.455, Recall: 0.455
Balanced Accuracy: 0.619, F1 Score: 0.541
Confusion Matrix:
 [[18  5]
 [12 10]]


Fold:  8, Training/Test Split Distribution: [205 198]
Accuracy: 0.500, Precision: 0.500, Specificity: 0.500, Sensitivity: 0.500, Recall: 0.500
Balanced Accuracy: 0.500, F1 Score: 0.500
Confusion Matrix:
 [[11 11]
 [11 11]]


Fold:  9, Training/Test Split Distribution: [205 198]
Accuracy: 0.659, Precision: 0.652, Specificity: 0.636, Sensitivity: 0.682, Recall: 0.682
Balanced Accuracy: 0.659, F1 Score: 0.667
Confusion Matrix:
 [[14  8]
 [ 7 15]]


Fold: 10, Training/Test Split Distribution: [205 198]
Accuracy: 0.841, Precision: 0.895, Specificity: 0.909, Sensitivity: 0.773, Recall: 0.773
Balanced Accuracy: 0.841, F1 Score: 0.829
Confusion Matrix:
 [[20  2]
 [ 5 17]]




Cross-Validation Accuracy: 0.636 +/- 0.136
Mean Accuracy: 0.636, Precision: 0.633, Specificity: 0.